version: "3.8"

services:
  eventcrafter:
    build:
      context: .
      target: production
    container_name: eventcrafter
    restart: unless-stopped
    environment:
      - BOT_TOKEN={{Токен бота из пункта 1}}
      - TIMEZONE=Europe/Moscow
      - DATABASE_URL=sqlite+aiosqlite:////data/eventcrafter.db
    volumes:
      - ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  tests:
    build:
      context: .
      target: tester
    container_name: eventcrafter_tests
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////tmp/test.db
    volumes:
      - ./test_results:/app/test_results
    working_dir: /app
    restart: "no"