version: "3.8"

services:
  bot:
    build:
      dockerfile: Dockerfile
    container_name: EventCrafter
    restart: unless-stopped
    environment:
      - BOT_TOKEN={Токен бота из пункта 1}
      - TIMEZONE=Europe/Moscow
    volumes:
      - ./data:/data