name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: docker build --target tester -t eventcrafter:test .

      - name: Run tests with annotations
        run: |
          docker run --rm eventcrafter:test \
            /bin/bash -c "pip install pytest-github-actions-annotate-failures && pytest tests/ -v --tb=short --log-cli-level=INFO"
